Initial GMPE tests
axelarnetwork/axelar-gmp-sdk-solidity pull request #28
Opened 2023-03-17 19:56 UTC by deanamiel

Initial GMPE tests, using hardhat in conjunction with waffle to detect custom errors

2023-03-30 12:55 UTC, milapsheth commented on hardhat.config.js
> +require('@nomicfoundation/hardhat-toolbox');
:+1:

2023-03-30 15:17 UTC, deanamiel commented on test/GMP.js
>  const ADDRESS_ZERO = '0x0000000000000000000000000000000000000000';
you're right, the import is implicit, I'll remove from each test file

2023-03-30 15:27 UTC, deanamiel commented on test/ConstAddressDeployer.js
> +    userWallet = wallets[1];
agreed, I'll make this correction in each test file

2023-03-30 15:37 UTC, deanamiel commented on test/ConstAddressDeployer.js
> +  let deployerFactory;
I use all the factory variables once to instantiate them in the before() hook and then again to deploy contracts in the beforeEach() hook so I think they need to be global to be accessible in both.

2023-03-30 15:48 UTC, deanamiel commented on test/GMP.js
>  const ADDRESS_ZERO = '0x0000000000000000000000000000000000000000';
when I remove it all tests still run smoothly but now there's a lint error each time "ethers" is referenced in the code

2023-03-31 15:59 UTC, milapsheth approved these changes

2023-03-31 16:53 UTC, re1ro requested changes
Could you please rename `DummyProxy` into `InvalidExpressProxy`  and the same for registry?

2023-04-03 13:14 UTC, re1ro approved these changes

2023-04-03 13:15 UTC, merged