feat: add contract verification helper
axelarnetwork/axelar-gmp-sdk-solidity pull request #34
Opened 2023-04-26 11:03 UTC by milapsheth

2023-05-03 13:40 UTC, sammy1991106 requested changes

2023-05-03 13:40 UTC, sammy1991106 commented on package.json
> +    "build": "rm -rf artifacts && rm -rf cache && hardhat compile && npm run copy:artifacts",
```suggestion
    "build": "rm -rf artifacts cache && hardhat compile && npm run copy:artifacts",
```

2023-05-03 13:40 UTC, sammy1991106 commented on scripts/utils.js
> +function importNetworks(chains, keys) {
```suggestion
const importNetworks = (chains, keys) => {
```

2023-05-03 13:40 UTC, sammy1991106 commented on scripts/utils.js
> +  printObj('Verified!');
```suggestion
  return writeFileAsync(file, content, 'utf-8')
    .then(() => {
      console.log(
        `Verifying contract ${contract} with args '${stringArgs.join(',')}'`,
      );
      console.log(cmd);

      return execAsync(cmd, { stdio: 'inherit' });
    })
    .then(() => {
      console.log('Verified!');
    });
```

2023-05-03 13:40 UTC, sammy1991106 commented on scripts/utils.js
> +  }
```suggestion
  const networks = {
    hardhat: {
      chainId: 31337, // default hardhat network chain id
    },
  };

  const etherscan = {
    apiKey: {},
    customChains: [],
  };

  // Add custom networks
  chains.forEach((chain) => {
    const name = chain.name.toLowerCase();
    networks[name] = {
      chainId: chain.chainId,
      id: chain.id,
      url: chain.rpc,
      blockGasLimit: chain.gasOptions?.gasLimit,
      accounts: keys.accounts || keys.chains[name]?.accounts,
    };

    // Add contract verification keys
    if (chain.explorer) {
      etherscan.apiKey[name] = keys.chains[name]?.api;

      etherscan.customChains.push({
        network: name,
        chainId: chain.chainId,
        urls: {
          apiURL: chain.explorer.api,
          browserURL: chain.explorer.url,
        },
      });
    }
  });
```

2023-05-03 13:40 UTC, sammy1991106 commented on scripts/utils.js
> +  var etherscan = {
never use `var` in js

2023-05-03 13:51 UTC, milapsheth commented on scripts/.example.keys.json
> +}
prettier config needs to be fixed for this repo, since my editor removes this automatically

2023-05-03 13:52 UTC, sammy1991106 commented on scripts/.example.keys.json
> +}
mine doesn't though

2023-05-03 13:53 UTC, sammy1991106 commented on scripts/utils.js
> +  printObj('Verified!');
You'd also need to fix where this function is being used as it returns a promise now.

2023-05-03 13:59 UTC, milapsheth commented on scripts/.example.keys.json
> +}
differing editor configs. We'll need to add a repo config to override editor defaults.

2023-05-03 14:45 UTC, sammy1991106 approved these changes

2023-05-03 14:45 UTC, sammy1991106 commented on scripts/upgradable.js
> +    await verifyContract(env, chain, proxy.address, proxyConstructorArgs);
```suggestion
    await Promise.all([
      verifyContract(
        env,
        chain,
        implementation.address,
        implementationConstructorArgs,
      ),
      verifyContract(env, chain, proxy.address, proxyConstructorArgs),
    ]);
```

2023-05-08 14:44 UTC, deanamiel approved these changes

2023-05-11 00:56 UTC, merged