feat: gmp express service
axelarnetwork/axelar-gmp-sdk-solidity pull request #36
Opened 2023-05-17 20:13 UTC by deanamiel

Moved GMPExpress PR to SDK repo. 

Main Changes:
- Moved ExpressService, ExpressServiceProxy, and ExpressProxyFactory to this repo
- Updated GMPE test to use ExpressService instead of a mock express service contract

TODO:
- Decide whether or not to remove ExpressProxyFactory
- Decide where we want info folder and deployment scripts to live

2023-05-19 18:03 UTC, re1ro requested changes

2023-05-19 18:03 UTC, re1ro commented on contracts/express/ExpressService.sol
> +        (, bytes memory data) = address(proxyDeployer).delegatecall(
@deanamiel could you please move this code right into `deployExpressProxy` since we don't reuse `_deployExpressProxy` anywhere else.

2023-06-20 23:43 UTC, re1ro approved these changes

2023-06-20 23:47 UTC, npty approved these changes

2023-06-20 23:50 UTC, merged